[features]
web_browsing = true
multi_agent = true
default_mode_request_user_input = true

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
http_headers = { "CONTEXT7_API_KEY" = "ctx7sk-7a97cef4-1507-467e-a384-6e3572f0ca42" }
